# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CKOeQnMXIUIlEtJrnozCBvuJjIS2j5v
"""

# Arquivo: app.py ( Versão Final e Corrigida)
import dash
import dash_bootstrap_components as dbc
from dash import Dash, html, dcc, Input, Output

# Lista de temas disponíveis
THEMES = {
    "Moderno (Litera)": dbc.themes.LITERA,
    "Padrão (Spacelab)": dbc.themes.SPACELAB,
    "Claro (Flatly)": dbc.themes.FLATLY,
    "Escuro (Cyborg)": dbc.themes.CYBORG,
    "Escuro (Darkly)": dbc.themes.DARKLY,
}

app = Dash(__name__, use_pages=True, external_stylesheets=[dbc.themes.LITERA])
server = app.server

# --- Layout da Barra Lateral ---
sidebar = dbc.Nav(
    [
        dbc.NavLink(
            html.Div([
                html.I(className="bi bi-house-door-fill me-2"),
                "Dashboard Principal"
            ]),
            href="/",
            active="exact",
        ),
        dbc.NavLink(
            html.Div([
                html.I(className="bi bi-graph-up-arrow me-2"),
                "Análise de Sensibilidade"
            ]),
            href="/analise-de-sensibilidade",
            active="exact",
        ),
        html.Hr(),
        dbc.Label("Mudar Tema Visual:"),
        dcc.Dropdown(
            id='theme-dropdown',
            options=[{'label': k, 'value': v} for k, v in THEMES.items()],
            value=dbc.themes.LITERA,
            clearable=False
        )
    ],
    vertical=True,
    pills=True,
    className="bg-light",
)

# --- Layout Geral do App ---
app.layout = dbc.Container(
    [
        # Os Stores são colocados aqui, no layout principal, para que
        # persistam entre as mudanças de página. Esta é a estrutura correta.
        dcc.Store(id='results-store'),
        dcc.Store(id='params-store-sensitivity'),

        html.Link(id='theme-link', rel='stylesheet', href=dbc.themes.LITERA),
        dbc.Row([
            dbc.Col(html.H2("🌱 Simulador Agrícola Estratégico", className="text-center bg-primary text-white p-2"), width=12)
        ]),
        dbc.Row(
            [
                dbc.Col(sidebar, width=2, className="bg-light"),
                # O conteúdo das suas páginas (home.py, etc.) será renderizado aqui.
                dbc.Col(dash.page_container, width=10),
            ],
            style={"marginTop": "10px"},
        ),
    ],
    fluid=True,
)

# Callback para atualizar o tema
@app.callback(
    Output('theme-link', 'href'),
    Input('theme-dropdown', 'value')
)
def update_theme(theme_url):
    return theme_url

if __name__ == "__main__":
    app.run(debug=True)